# Generated by Django 2.2.3 on 2019-09-16 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=400)),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('last_achievement_name', models.CharField(default='No achievements yet', max_length=100)),
                ('last_achievement_time', models.DateField(null=True)),
                ('last_code', models.CharField(default='None', max_length=100)),
                ('is_mentor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='triv_tracker_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('last_achievement_name', models.CharField(default='No achievements yet', max_length=100)),
                ('last_achievement_time', models.DateField(null=True)),
                ('last_code', models.CharField(default='None', max_length=100)),
                ('is_mentor', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AchievementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loops_2', models.BooleanField(default=False)),
                ('loops_1', models.BooleanField(default=False)),
                ('control_flow', models.BooleanField(default=False)),
                ('strings', models.BooleanField(default=False)),
                ('variables', models.BooleanField(default=False)),
                ('hello_world', models.BooleanField(default=False)),
                ('get_installed', models.BooleanField(default=False)),
                ('lightning_talk', models.BooleanField(default=False)),
                ('pair_up', models.BooleanField(default=False)),
                ('html_page', models.BooleanField(default=False)),
                ('technical_mentor', models.BooleanField(default=False)),
                ('let_me_teach', models.BooleanField(default=False)),
                ('attention', models.BooleanField(default=False)),
                ('hear_ye', models.BooleanField(default=False)),
                ('complete_1_level', models.BooleanField(default=False)),
                ('complete_1_game', models.BooleanField(default=False)),
                ('basic_output', models.BooleanField(default=False)),
                ('html_basics_1', models.BooleanField(default=False)),
                ('css_basics', models.BooleanField(default=False)),
                ('html_basics_2', models.BooleanField(default=False)),
                ('html_basics_3', models.BooleanField(default=False)),
                ('html_basics_4', models.BooleanField(default=False)),
                ('html_basics_5', models.BooleanField(default=False)),
                ('respond_to_events', models.BooleanField(default=False)),
                ('to_do', models.BooleanField(default=False)),
                ('click', models.BooleanField(default=False)),
                ('keypress', models.BooleanField(default=False)),
                ('mouse_jump', models.BooleanField(default=False)),
                ('on_the_move', models.BooleanField(default=False)),
                ('motion_sickness', models.BooleanField(default=False)),
                ('show_an_understanding_of_pen', models.BooleanField(default=False)),
                ('functions', models.BooleanField(default=False)),
                ('sprites', models.BooleanField(default=False)),
                ('graphic_effects', models.BooleanField(default=False)),
                ('pow_boing', models.BooleanField(default=False)),
                ('background', models.BooleanField(default=False)),
                ('program_a_game', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
