# Generated by Django 2.2.3 on 2019-09-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0002_auto_20190916_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementrecord',
            old_name='achievement1',
            new_name='achievement_1',
        ),
        migrations.RenameField(
            model_name='achievementrecord',
            old_name='achievement2',
            new_name='achievement_2',
        ),
        migrations.RenameField(
            model_name='achievementrecord',
            old_name='achievement3',
            new_name='achievement_3',
        ),
    ]
