# Generated by Django 2.2.3 on 2019-08-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0003_auto_20190821_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PointSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
