# Generated by Django 2.2.3 on 2019-08-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0006_achievement_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='reward',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='MentorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='triv_tracker_app.UserProfile')),
            ],
        ),
    ]
