# Generated by Django 2.2.3 on 2019-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0007_auto_20190821_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
