# Generated by Django 2.2.3 on 2019-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0008_auto_20190821_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
