# Generated by Django 2.2.3 on 2019-08-21 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0009_achievement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='last_achievement_time',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 18, 25, 26, 284783)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_achievement_time',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 18, 25, 26, 284783)),
        ),
    ]
