# Generated by Django 2.2.3 on 2019-08-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0011_auto_20190822_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='last_achievement_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_achievement_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_achievement_time',
            field=models.DateField(null=True),
        ),
    ]
