# Generated by Django 2.2.3 on 2019-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0013_auto_20190906_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='achievementrecord',
            name='username',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
