# Generated by Django 2.2.3 on 2019-09-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0014_auto_20190906_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_achievement_id',
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='last_achievement_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_achievement_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
