# Generated by Django 2.2.3 on 2019-09-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0016_auto_20190906_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='last_achievement_name',
            field=models.CharField(db_index=True, default='No achievements yet!', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_achievement_name',
            field=models.CharField(default='No achievements yet!', max_length=200, unique=True),
        ),
    ]
