# Generated by Django 2.2.3 on 2019-09-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0019_auto_20190906_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='last_achievement_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_achievement_name',
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=1),
        ),
    ]
