# Generated by Django 2.2.3 on 2019-09-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0021_auto_20190906_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=1),
        ),
    ]
