# Generated by Django 2.2.3 on 2019-09-06 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0022_auto_20190906_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
            field=models.IntegerField(db_index=True, default=uuid.uuid1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=uuid.uuid1, unique=True),
        ),
    ]
