# Generated by Django 2.2.3 on 2019-09-06 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0023_auto_20190906_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=uuid.uuid1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_achievement_id',
            field=models.IntegerField(default=uuid.uuid1, null=True),
        ),
    ]
