# Generated by Django 2.2.3 on 2019-09-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0024_auto_20190906_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='last_achievement_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_achievement_id',
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='last_achievement_name',
            field=models.CharField(default='No achievements yet', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_achievement_name',
            field=models.CharField(default='No achievements yet', max_length=100),
        ),
    ]
