# Generated by Django 2.2.3 on 2019-09-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triv_tracker_app', '0027_updatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='last_code',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_code',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
